### ISSUE TITLE
Incompatible with pjax

### ISSUE THREAD

**Issue by wangjiezhe** [theme-next/hexo-next-utteranc#4]
When enable pjax, utterances only loads when the whole page is reloaded, but doesn't work when jumping from another page.

当使用 Pjax 时，如果通过首页点击文章链接进入文章页面，utterances 不会加载，只有再次刷新页面才会加载。或者直接输入文章链接，utterances 可以正常加载，但在跳转到其他文章后又不会自动加载了。

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/next-theme/hexo-theme-next/commit/7e498954705b9e954c2af4b284cc69d5e66341a2

**Comment by wangjiezhe** [comment]
目前和 pjax 依然不兼容。跳转文章之后，utterances 显示的评论还是上一篇文章的评论。

**Comment by Brannua** [comment]
support pjax ? I use the latest version of utteranc & hexo-next-utteranc in chrome on Linux. Thanks.
